apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: posts.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: posts-frontend-srv
                port: 
                  number: 4002
